package view;

import control.DienThoaiEX;
import control.IOFile;
import control.KhongTrongEX;
import control.SoLuongEx;
import java.io.File;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BanDoc;
import model.QLMS;
import model.Sach;

/**
 *
 * @author phamc
 */
public class Main_Sach extends javax.swing.JFrame {
    private boolean  them ,sua ; 
    private String fileSach ; 
    private  List<Sach> lsach ; 
    DefaultTableModel tbl ; 
    
    private boolean  them1 ,sua1 ; 
    private String fileBanDoc ; 
    private  List<BanDoc> lbandoc ; 
    DefaultTableModel tbl1 ; 
    
    private String fileQlms ; 
    private  List<QLMS> lqlms ; 
    DefaultTableModel tbl2 ; 
    
    
    public Main_Sach() {
        initComponents();
        setLocationRelativeTo(null);
        
        String nameColString[] = {"Ma sach" , "Ten Sach" , "Tac Gia" , "Chuyen Nganh" , "So Luong"} ; 
        tbl  = new DefaultTableModel(nameColString, 0);
        jTable1.setModel(tbl);
        trangthai(true);
        them  = false ; 
        sua  = false ; 
        fileSach = "src/sach.txt" ; 
        
        String nameColString1[] = {"Ma Ban Doc" , "Ho Va Ten" , "Dia Chi" , "So Dien Thoai" } ; 
        tbl1  = new DefaultTableModel(nameColString1, 0);
        jTable2.setModel(tbl1);
        trangthai1(true);
        them1  = false ; 
        sua1  = false ; 
        fileBanDoc = "src/bandoc.txt" ; 
        
        
        String nameColString2[] = {"Ma Ban Doc" , "Ho Va Ten" , "Ma Sach" , "So luong" , "Tinh Trang" } ; 
        tbl2  = new DefaultTableModel(nameColString2, 0);
        jTable3.setModel(tbl2);
        fileQlms = "src/QLMS.txt" ; 
        
        loadData();
        load2ma();
        
        
        
    }
    
    private void loadData(){
        File t  = new File(fileSach) ; 
        if(t.exists()){
            lsach = IOFile.doc(fileSach) ; 
            tbl.setRowCount(0);
            for (Sach sach : lsach) {
                 tbl.addRow(sach.toObject());
            }
        } else {
            lsach  = new ArrayList<>() ; 
        }
        
        File t1  = new File(fileBanDoc) ; 
        if(t1.exists()){
            lbandoc = IOFile.doc(fileBanDoc) ; 
            tbl1.setRowCount(0);
        for (BanDoc bandoc : lbandoc) {
            tbl1.addRow(bandoc.toObject());
            }
        } else {
            lbandoc  = new ArrayList<>() ; 
        }
             
        
        File t2  = new File(fileQlms) ; 
        if(t2.exists()){
            lqlms = IOFile.doc(fileQlms) ; 
            tbl2.setRowCount(0);
            for (QLMS qlms : lqlms) {
                tbl2.addRow(qlms.toObject());
            }
        } else {
            lqlms  = new ArrayList<>() ; 
        }
    }
    
    private void trangthai(Boolean b){
        THEM.setEnabled(b); 
        CAPNHAT.setEnabled(!b);
        BOQUA.setEnabled(!b);
    }
    
       private void trangthai1(Boolean b){
        THEM1.setEnabled(b); 
        CAPNHAT1.setEnabled(!b);
        BOQUA1.setEnabled(!b);
    }
       private Boolean trung2ma(int mabandoc ,int masach){
           for (QLMS qlms : lqlms) {
               if(qlms.getBandoc().getMa() == mabandoc && qlms.getSach().getMasach() == masach) return true ; 
           }
           return false  ; 
       }
       private  int demdausach(int mabandoc){
           int count  = 0 ; 
           for (QLMS lqlm : lqlms) {
               if(lqlm.getBandoc().getMa() == mabandoc) count++ ; 
           }
           return count ; 
       }
       private  void load2ma(){
           jComboBox2.removeAllItems();
           jComboBox3.removeAllItems();
           List<BanDoc> l1 = IOFile.doc(fileBanDoc) ; 
           List<Sach> l2 = IOFile.doc(fileSach) ; 
                for (BanDoc banDoc : l1) {
                  jComboBox2.addItem(banDoc.getMa()+"");
                 }
                 for (Sach sach : l2) {
                           jComboBox3.addItem(sach.getMasach()+"");
                 }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        THEM = new javax.swing.JButton();
        SUA = new javax.swing.JButton();
        XOA = new javax.swing.JButton();
        CAPNHAT = new javax.swing.JButton();
        BOQUA = new javax.swing.JButton();
        HIENTHI = new javax.swing.JButton();
        LUUVAOFILE = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        THEM1 = new javax.swing.JButton();
        SUA1 = new javax.swing.JButton();
        XOA1 = new javax.swing.JButton();
        CAPNHAT1 = new javax.swing.JButton();
        BOQUA1 = new javax.swing.JButton();
        HIENTHI1 = new javax.swing.JButton();
        LUUVAOFILE1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        LAMMOI = new javax.swing.JButton();
        THEM2 = new javax.swing.JButton();
        HIENTHI2 = new javax.swing.JButton();
        LUUVAOFILE2 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quan Ly Sach");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Ma Sach");

        jLabel3.setText("Ten Sach");

        jLabel4.setText("Tac Gia");

        jLabel5.setText("Chuyen nganh");

        jLabel6.setText("So Luong");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa Hoc Tu Nhien", "Van Hoc - Nghe Thuat", "Dien Tu Vien Thong", "Cong Nghe Thong Tin" }));

        THEM.setText("Them");
        THEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THEMActionPerformed(evt);
            }
        });

        SUA.setText("Sua");
        SUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUAActionPerformed(evt);
            }
        });

        XOA.setText("Xoa");
        XOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XOAActionPerformed(evt);
            }
        });

        CAPNHAT.setText("Cap Nhat");
        CAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAPNHATActionPerformed(evt);
            }
        });

        BOQUA.setText("Bo Qua");
        BOQUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOQUAActionPerformed(evt);
            }
        });

        HIENTHI.setText("Hien Thi");
        HIENTHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIENTHIActionPerformed(evt);
            }
        });

        LUUVAOFILE.setText("Luu Vao File");
        LUUVAOFILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUUVAOFILEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(32, 32, 32)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BOQUA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(THEM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HIENTHI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SUA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(XOA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(CAPNHAT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LUUVAOFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(THEM)
                        .addComponent(SUA))
                    .addComponent(XOA)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CAPNHAT)
                        .addComponent(BOQUA)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HIENTHI)
                    .addComponent(LUUVAOFILE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Sach", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        THEM1.setText("Them");
        THEM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THEM1ActionPerformed(evt);
            }
        });

        SUA1.setText("Sua");
        SUA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUA1ActionPerformed(evt);
            }
        });

        XOA1.setText("Xoa");
        XOA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XOA1ActionPerformed(evt);
            }
        });

        CAPNHAT1.setText("Cap Nhat");
        CAPNHAT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAPNHAT1ActionPerformed(evt);
            }
        });

        BOQUA1.setText("Bo Qua");
        BOQUA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOQUA1ActionPerformed(evt);
            }
        });

        HIENTHI1.setText("Hien Thi");
        HIENTHI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIENTHI1ActionPerformed(evt);
            }
        });

        LUUVAOFILE1.setText("Luu Vao File");
        LUUVAOFILE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUUVAOFILE1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ma Ban Doc");

        jLabel8.setText("Ho Va Ten");

        jLabel9.setText("Dia Chi");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel10.setText("So Dien Thoai");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(BOQUA1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(THEM1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HIENTHI1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SUA1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(XOA1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(CAPNHAT1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LUUVAOFILE1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(THEM1)
                        .addComponent(SUA1))
                    .addComponent(XOA1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CAPNHAT1)
                        .addComponent(BOQUA1)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HIENTHI1)
                    .addComponent(LUUVAOFILE1))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("BanDoc", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel11.setText("Ma Ban Doc");

        jLabel12.setText("Ma Ban Doc");

        jLabel13.setText("Ma Sach");

        jLabel14.setText("Trinh Trang");

        jLabel15.setText("So Luong");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LAMMOI.setText("LAM MOI");
        LAMMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAMMOIActionPerformed(evt);
            }
        });

        THEM2.setText("THEM");
        THEM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THEM2ActionPerformed(evt);
            }
        });

        HIENTHI2.setText("HIen Thi");
        HIENTHI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIENTHI2ActionPerformed(evt);
            }
        });

        LUUVAOFILE2.setText("Luu Vao File");
        LUUVAOFILE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUUVAOFILE2ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Lua chon sap xep ---", "Theo ten", "Theo So luong" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LAMMOI, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(THEM2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(HIENTHI2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(LUUVAOFILE2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 109, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(393, 393, 393)
                    .addComponent(jLabel11)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(THEM2)
                            .addComponent(HIENTHI2)
                            .addComponent(LUUVAOFILE2)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(LAMMOI)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(jLabel11)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("QuanLyMuonSach", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void LUUVAOFILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUUVAOFILEActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fileSach, lsach);
    }//GEN-LAST:event_LUUVAOFILEActionPerformed

    private void HIENTHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIENTHIActionPerformed
      //   TODO add your handling code here:
        loadData(); 
//        lsach = IOFile.doc(fileSach ); 
//        tbl.setRowCount(0);
//        for (Sach sach : lsach) {
//            tbl.addRow(sach.toObject());
//        }
        
    }//GEN-LAST:event_HIENTHIActionPerformed

    private void THEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THEMActionPerformed
        // TODO add your handling code here:
        trangthai(false);
        them = true ; 
        File t = new File(fileSach) ; 
        if(lsach!=null && lsach.size()>0){
            Sach.setSma(lsach.get(lsach.size()-1).getMasach() + 1);
        } else {
            lsach = new ArrayList<>() ;     
        }
        jTextField1.setText(Sach.getSma()+"");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
        jTextField2.requestFocus();
        
    }//GEN-LAST:event_THEMActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row  = jTable1.getSelectedRow() ; 
        jTextField1.setText(tbl.getValueAt(row, 0).toString());
        jTextField2.setText(tbl.getValueAt(row, 1).toString());
        jTextField3.setText(tbl.getValueAt(row, 2).toString());
        jTextField4.setText(tbl.getValueAt(row, 4).toString());
        String cn = tbl.getValueAt(row, 3).toString() ; 
        for(int i = 0 ; i<jComboBox1.getItemCount() ; i++){
            if(jComboBox1.getItemAt(i).toString().equals(cn)){
                jComboBox1.setSelectedItem(i);
                break ; 
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void BOQUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOQUAActionPerformed
        // TODO add your handling code here:
        if(them == true ) them  = false ; 
        trangthai(true);
        if(sua == true) sua = false ; 
    }//GEN-LAST:event_BOQUAActionPerformed

    private void XOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XOAActionPerformed
        // TODO add your handling code here:
        int row  = jTable1.getSelectedRow()  ; 
        if(row < 0 || row > jTable1.getRowCount()){
            JOptionPane.showMessageDialog(this, "Chon Sach De Sua");
        } else {
            tbl.removeRow(row);
            lsach.remove(row) ; 
        }
    }//GEN-LAST:event_XOAActionPerformed

    private void SUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUAActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow() ; 
        if(row < 0 || row > jTable1.getRowCount()){
            JOptionPane.showMessageDialog(this, "Chon Sach de sua");
        } else {
            sua = true ; 
            trangthai(false);
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_SUAActionPerformed

    private void CAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAPNHATActionPerformed
        // TODO add your handling code here:
        if(them == true ){
            String ten , tacgia ; 
            int soluong , ma ; 
            try {
                ten = jTextField2.getText() ; 
                tacgia = jTextField3.getText()  ; 
                if( ten.isEmpty() ||tacgia.isEmpty() ) throw  new KhongTrongEX() ; 
                soluong = Integer.parseInt(jTextField4.getText()) ; 
                if(soluong<0) throw  new SoLuongEx() ; 
                ma = Integer.parseInt(jTextField1.getText()) ; 
                Sach t = new Sach(ma, ten, tacgia, jComboBox1.getSelectedItem().toString() , soluong) ; 
                tbl.addRow(t.toObject());
                lsach.add(t) ; 
                them = false ; 
                trangthai(true);
            } catch (KhongTrongEX e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } catch (NumberFormatException t){
              JOptionPane.showMessageDialog(this, "Nhap Vao So");
            }catch (SoLuongEx t){
                       JOptionPane.showMessageDialog(this, "Nhap So Duong");
            } 
        }
        if(sua == true ){
            int row = jTable1.getSelectedRow() ; 
            String tensach , tacgia , cn  ; 
            int soluong  , ma ; 
            try {
                tensach = jTextField2.getText() ; 
                tacgia = jTextField3.getText() ; 
                if(tensach.isEmpty() || tacgia.isEmpty() ) throw  new KhongTrongEX() ; 
                soluong = Integer.parseInt(jTextField4.getText()) ; 
                if(soluong <0) throw new SoLuongEx() ; 
                ma = Integer.parseInt(jTextField1.getText()) ; 
                cn = jComboBox1.getSelectedItem().toString() ; 
                Sach t = new Sach(ma , tensach , tacgia , cn , soluong) ; 
                lsach.set(row, t) ; 
                jTable1.setValueAt(tensach, row, 1);
                jTable1.setValueAt(tacgia, row, 2);
                jTable1.setValueAt(cn, row, 3);
                jTable1.setValueAt(soluong, row, 4);
                sua  = false ; 
                trangthai(true);
             } catch (KhongTrongEX e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } catch (NumberFormatException t){
              JOptionPane.showMessageDialog(this, "Nhap Vao So");

            } catch (SoLuongEx t){
                    JOptionPane.showMessageDialog(this, "Nhap So Duong");
            }
        }
    }//GEN-LAST:event_CAPNHATActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row  = jTable2.getSelectedRow() ; 
        jTextField5.setText(tbl1.getValueAt(row, 0).toString());
        jTextField6.setText(tbl1.getValueAt(row, 1).toString());
        jTextField7.setText(tbl1.getValueAt(row, 2).toString());
        jTextField8.setText(tbl1.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void THEM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THEM1ActionPerformed
        // TODO add your handling code here:
        trangthai1(false);
        them1 = true ; 
        File t = new File(fileBanDoc) ; 
        if(lbandoc!=null && lbandoc.size()>0){
            BanDoc.setSma(lbandoc.get(lbandoc.size()-1).getMa()+ 1);
        } else {
            lbandoc = new ArrayList<>() ;     
        }
        jTextField5.setText(BanDoc.getSma()+"");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        
        jTextField6.requestFocus();
    }//GEN-LAST:event_THEM1ActionPerformed

    private void SUA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUA1ActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow() ; 
        if(row < 0 || row > jTable2.getRowCount()){
            JOptionPane.showMessageDialog(this, "Chon Ban Doc de sua");
        } else {
            sua1 = true ; 
            trangthai1(false);
            jTextField6.requestFocus();
        }
    }//GEN-LAST:event_SUA1ActionPerformed

    private void XOA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XOA1ActionPerformed
        // TODO add your handling code here:
        int row  = jTable2.getSelectedRow()  ; 
        if(row < 0 || row > jTable2.getRowCount()){
            JOptionPane.showMessageDialog(this, "Chon Ban Doc De Xoa");
        } else {
            tbl1.removeRow(row);
            lbandoc.remove(row) ; 
        }
    }//GEN-LAST:event_XOA1ActionPerformed

    private void CAPNHAT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAPNHAT1ActionPerformed
        // TODO add your handling code here:
        if(them1 == true ){
            String hoten , diachi , sdt ; 
            try {
                hoten = jTextField6.getText() ; 
                diachi = jTextField7.getText()  ; 
                sdt = jTextField8.getText() ; 
                if( hoten.isEmpty() ||diachi.isEmpty() ||sdt.isEmpty()  ) throw  new KhongTrongEX() ; 
                String res = "\\d+" ; 
                if(!sdt.matches(res)) throw  new DienThoaiEX() ; 
                int ma = Integer.parseInt(jTextField5.getText()) ; 
                BanDoc t = new BanDoc(ma, hoten, diachi, sdt) ; 
                tbl1.addRow(t.toObject());
                lbandoc.add(t) ; 
                them1 = false ; 
                trangthai1(true);
            } catch (KhongTrongEX e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } catch (DienThoaiEX t){
              JOptionPane.showMessageDialog(this, "Nhap SDT dung dinh dang");
            }
        }
        if(sua1 == true ){
            int row = jTable2.getSelectedRow() ; 
            String hoten , diachiString, sdt  ; 
            try {
                hoten = jTextField6.getText() ; 
                diachiString = jTextField7.getText() ;
                sdt = jTextField8.getText() ; 
                if(hoten.isEmpty() || diachiString.isEmpty() || sdt.isEmpty() ) throw  new KhongTrongEX() ; 
                 String res = "\\d+" ; 
                if(!sdt.matches(res)) throw  new DienThoaiEX() ; 
                int ma = Integer.parseInt(jTextField5.getText()) ; 
                BanDoc t = new BanDoc(ma , hoten , diachiString , sdt  ) ; 
                lbandoc.set(row, t) ; 
                jTable2.setValueAt(hoten, row, 1);
                jTable2.setValueAt(diachiString, row, 2);
                jTable2.setValueAt(sdt, row, 3);
                sua1  = false ; 
                trangthai1(true);
             }catch (KhongTrongEX e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } catch (DienThoaiEX t){
              JOptionPane.showMessageDialog(this, "Nhap SDT dung dinh dang");
            }
        }
    }//GEN-LAST:event_CAPNHAT1ActionPerformed

    private void BOQUA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOQUA1ActionPerformed
        // TODO add your handling code here:
        if(them1 == true ) them1  = false ; 
        trangthai1(true);
        if(sua1 == true) sua1 = false ; 
    }//GEN-LAST:event_BOQUA1ActionPerformed

    private void HIENTHI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIENTHI1ActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_HIENTHI1ActionPerformed

    private void LUUVAOFILE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUUVAOFILE1ActionPerformed
        // TODO add your handling code here:
              IOFile.viet(fileBanDoc, lbandoc);

    }//GEN-LAST:event_LUUVAOFILE1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void LAMMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAMMOIActionPerformed
        // TODO add your handling code here:
        load2ma();
    }//GEN-LAST:event_LAMMOIActionPerformed
    private Sach getSachbyma(int ma){
            
                 for (Sach sach : lsach) {
                     if(sach.getMasach() == ma) return sach ; 
                 }  
                 return null ; 
    }
      private BanDoc getbandocbyma(int ma){
                 for (BanDoc sach : lbandoc) {
                     if(sach.getMa() == ma) return sach ; 
                 }   
                 return  null ; 
    }
    private void THEM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THEM2ActionPerformed
        // TODO add your handling code here:
        int mabandoc  = Integer.parseInt(jComboBox2.getSelectedItem().toString()) ; 
        int masach  = Integer.parseInt(jComboBox3.getSelectedItem().toString()) ; 
        if(trung2ma(mabandoc, masach) == true){
            JOptionPane.showMessageDialog(this, "Trung 2 ma");
            jComboBox2.requestFocus(); 
            return; 
        }
        if(demdausach(mabandoc)==5 ){
            JOptionPane.showMessageDialog(this, "Khong Duoc Muon Qua 5 Dau Sach");
            jComboBox2.requestFocus(); 
            return;
        }
        int soluong = 0 ; 
        int soluongconlai = getSachbyma(masach).getSoluong();
        try {
             soluong =  Integer.parseInt(jTextField9.getText().toString()) ; 
             if(soluong > soluongconlai){
                     JOptionPane.showMessageDialog(this, "Khong Du So Sach De Muon");
                    jTextField9.requestFocus();
                 return ; 
             }
             QLMS T = new QLMS(getbandocbyma(mabandoc) , getSachbyma(masach) , soluong , jTextField9.getText()) ;
             lqlms.add(T) ; 
             tbl2.addRow(T.toObject());
             getSachbyma(masach).setSoluong(soluongconlai-soluong);
             IOFile.viet(fileSach, lsach);
             
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Nhap Vao So");
             jTextField9.requestFocus();
                  return ; 
        }
        
    }//GEN-LAST:event_THEM2ActionPerformed

    private void HIENTHI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIENTHI2ActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_HIENTHI2ActionPerformed

    private void LUUVAOFILE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUUVAOFILE2ActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fileQlms, lqlms);
    }//GEN-LAST:event_LUUVAOFILE2ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox4.getSelectedIndex()== 1){ // theo ten
            lqlms.sort(new Comparator<QLMS>(){
                @Override
                public int compare(QLMS o1, QLMS o2) {
                    String []ten1 = o1.getBandoc().getHoten().split("\\s+") ; 
                    String []ten2 = o2.getBandoc().getHoten().split("\\s+") ; 
                    if(ten1[ten1.length-1].equalsIgnoreCase(ten2[ten2.length-1])){
                        return o1.getBandoc().getHoten().compareToIgnoreCase(o2.getBandoc().getHoten()) ; 
                    } else {
                        return ten1[ten1.length-1].compareToIgnoreCase(ten2[ten2.length-1]) ; 
                    }
                }
            
        });
        } 
        if(jComboBox4.getSelectedIndex() == 2){ // theo so luong
                lqlms.sort(new Comparator<QLMS>(){
                @Override
                public int compare(QLMS o1, QLMS o2) {
                   return Integer.compare(o1.getSoluong(), o2.getSoluong()) ; 
                }
                });
        }
        IOFile.viet(fileQlms, lqlms);
        loadData();
    }//GEN-LAST:event_jComboBox4ItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Sach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOQUA;
    private javax.swing.JButton BOQUA1;
    private javax.swing.JButton CAPNHAT;
    private javax.swing.JButton CAPNHAT1;
    private javax.swing.JButton HIENTHI;
    private javax.swing.JButton HIENTHI1;
    private javax.swing.JButton HIENTHI2;
    private javax.swing.JButton LAMMOI;
    private javax.swing.JButton LUUVAOFILE;
    private javax.swing.JButton LUUVAOFILE1;
    private javax.swing.JButton LUUVAOFILE2;
    private javax.swing.JButton SUA;
    private javax.swing.JButton SUA1;
    private javax.swing.JButton THEM;
    private javax.swing.JButton THEM1;
    private javax.swing.JButton THEM2;
    private javax.swing.JButton XOA;
    private javax.swing.JButton XOA1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
