package view;

import control.IOFile;
import control.TrongException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.LoaiVe;
import model.NguoiMuaVe;


/**
 *
 * @author phamc
 */
public class main4 extends javax.swing.JFrame {
    private List<LoaiVe> listLV ; 
    private List<NguoiMuaVe> listNMV ;  
    private  DefaultTableModel tblNMV , tblLV  ; 
    private String fileNMV , fileLV ; 
    
    public main4() {
        initComponents();
        setLocationRelativeTo(null);
        fileNMV= "src/model/NMV.dat" ; 
        fileLV = "src/model/LV.dat" ; 
        String nameNMV[] = new String[]{
           "Ma nguoi mua" , "Ho ten" , "Dia chi" , "Loai" 
       } ; 
       String namenLV[] = new String[]{
            "Ma ve" , "Loai ve" , "Don Gia" 
       } ; 
       tblNMV = new DefaultTableModel(nameNMV , 0) ; 
       tblLV = new DefaultTableModel(namenLV , 0) ;
       nguoimuaveTABLE.setModel(tblNMV);
       vemaybayTABLE.setModel(tblLV);
       
      loadLV(); loadNMV();
        showLV(listLV); showNMV(listNMV);
        
    }

      private void loadNMV() { 
        File f = new File(fileNMV) ; 
        if(f.exists()){
            listNMV = IOFile.doc(fileNMV) ; 
        } else {
            listNMV = new ArrayList<>() ; 
        }
    }
    private void loadLV() { 
        File f = new File(fileLV) ; 
        if(f.exists()){
            listLV = IOFile.doc(fileLV) ; 
        } else {
            listLV = new ArrayList<>() ; 
        }  
    }
     private void showLV(List<LoaiVe> list){
        tblLV.setRowCount(0);
         for (LoaiVe loaiVe : list) {
             tblLV.addRow(loaiVe.toObject());
         }
    }
    private void showNMV(List<NguoiMuaVe> list){
        tblNMV.setRowCount(0);
        for (NguoiMuaVe nguoiMuaVe : list) {
            tblNMV.addRow(nguoiMuaVe.toObject());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nguoimuaveTABLE = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diachimuaveTXT = new javax.swing.JTextField();
        hotenmuaveTXT = new javax.swing.JTextField();
        mamuaveTXT = new javax.swing.JTextField();
        loaiveBOX = new javax.swing.JComboBox<>();
        themmuaveBTN = new javax.swing.JButton();
        xoamuaveBTN = new javax.swing.JButton();
        ghivaofilemuaveBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dongiaTXT = new javax.swing.JTextField();
        maveTXT = new javax.swing.JTextField();
        loaivemaybayBOX = new javax.swing.JComboBox<>();
        ghivaofileveBTN = new javax.swing.JButton();
        suaveBTN = new javax.swing.JButton();
        themveBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vemaybayTABLE = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nguoimuaveTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(nguoimuaveTABLE);

        jLabel1.setText("Ma");

        jLabel2.setText("HoTen");

        jLabel3.setText("Dia Chi");

        jLabel4.setText("loai");

        mamuaveTXT.setEditable(false);

        loaiveBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mua lẻ", "mua tập thể", "mua qua mạng" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diachimuaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotenmuaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mamuaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiveBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mamuaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(diachimuaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(loaiveBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hotenmuaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        themmuaveBTN.setText("Them");
        themmuaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themmuaveBTNActionPerformed(evt);
            }
        });

        xoamuaveBTN.setText("Xoa");
        xoamuaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoamuaveBTNActionPerformed(evt);
            }
        });

        ghivaofilemuaveBTN.setText("Ghi Vao File");
        ghivaofilemuaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghivaofilemuaveBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(themmuaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(xoamuaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(ghivaofilemuaveBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themmuaveBTN)
                            .addComponent(xoamuaveBTN)
                            .addComponent(ghivaofilemuaveBTN))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nguoi Mua Ve", jPanel1);

        jLabel6.setText("Ma ve");

        jLabel7.setText("Loai ve");

        jLabel8.setText("Don gia");

        dongiaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongiaTXTActionPerformed(evt);
            }
        });

        maveTXT.setEditable(false);

        loaivemaybayBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doanh nhan", "Pho thong", "pho thong gia re", "the vàng", "the xanh", "ngoai giao" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dongiaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(maveTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(loaivemaybayBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loaivemaybayBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dongiaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        ghivaofileveBTN.setText("Ghi Vao File");
        ghivaofileveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghivaofileveBTNActionPerformed(evt);
            }
        });

        suaveBTN.setText("Sua");
        suaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaveBTNActionPerformed(evt);
            }
        });

        themveBTN.setText("Them");
        themveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themveBTNActionPerformed(evt);
            }
        });

        vemaybayTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(vemaybayTABLE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(themveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(suaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(ghivaofileveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themveBTN)
                            .addComponent(suaveBTN)
                            .addComponent(ghivaofileveBTN))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loai Ve May Bay", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hoa Don", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dongiaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongiaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dongiaTXTActionPerformed

    private void themmuaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themmuaveBTNActionPerformed
        // TODO add your handling code here:
        int  n = listNMV.size() ; 
        if(n>0){
            NguoiMuaVe.setSma(listNMV.get(n-1).getMa() + 1);
        }
        maveTXT.setText(NguoiMuaVe.getSma() + "");
        String ten , diachi , loai; 
        
        try {
            ten = maveTXT.getText() ; 
            diachi = diachimuaveTXT.getText() ; 
            loai = loaiveBOX.getSelectedItem().toString() ; 
            NguoiMuaVe d = new NguoiMuaVe(ten , diachi , loai) ; 
            tblNMV.addRow(d.toObject());
            listNMV.add(d); 
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "Khong de trong");
        } 
        
    }//GEN-LAST:event_themmuaveBTNActionPerformed

    private void xoamuaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoamuaveBTNActionPerformed
        // TODO add your handling code here:
        int tick = nguoimuaveTABLE.getSelectedRow() ; 
       if(tick <0 || tick > nguoimuaveTABLE.getRowCount()){
                       JOptionPane.showMessageDialog(this, "Chon Nguoi mua ve");
                       return ; 
       }  
       tblNMV.removeRow(tick);
       listNMV.remove(tick) ; 
    }//GEN-LAST:event_xoamuaveBTNActionPerformed

    private void ghivaofilemuaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghivaofilemuaveBTNActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fileNMV, listNMV);
    }//GEN-LAST:event_ghivaofilemuaveBTNActionPerformed

    private void themveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themveBTNActionPerformed
        // TODO add your handling code here:
             int  n = listLV.size() ; 
        if(n>0){
           LoaiVe.setSma(listLV.get(n-1).getMa() + 1);
        }
        maveTXT.setText(LoaiVe.getSma() + "");
        String ten ,  loai ; 
        int dongia ; 
        try {
            ten = maveTXT.getText() ; 
            dongia = Integer.parseInt(dongiaTXT.getText().toString()) ; 
            loai = loaivemaybayBOX.getSelectedItem().toString() ; 
            LoaiVe d = new LoaiVe( loai , dongia) ; 
            tblLV.addRow(d.toObject());
            listLV.add(d); 
        } catch (NumberFormatException t) {
            JOptionPane.showMessageDialog(this, "Nhap So.");
        }
    }//GEN-LAST:event_themveBTNActionPerformed

    private void suaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaveBTNActionPerformed
        // TODO add your handling code here:
        int t = vemaybayTABLE.getSelectedRow() ; 
        if(t<0 || t> vemaybayTABLE.getRowCount()) {
                        JOptionPane.showMessageDialog(this, "Hay chon de sua"); return;
        }
        vemaybayTABLE.setValueAt(loaivemaybayBOX.getSelectedItem().toString(), t, 1);
        vemaybayTABLE.setValueAt(dongiaTXT.toString(), t, 2);
    }//GEN-LAST:event_suaveBTNActionPerformed

    private void ghivaofileveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghivaofileveBTNActionPerformed
        // TODO add your handling code here:
         IOFile.viet(fileLV, listLV);

    }//GEN-LAST:event_ghivaofileveBTNActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diachimuaveTXT;
    private javax.swing.JTextField dongiaTXT;
    private javax.swing.JButton ghivaofilemuaveBTN;
    private javax.swing.JButton ghivaofileveBTN;
    private javax.swing.JTextField hotenmuaveTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> loaiveBOX;
    private javax.swing.JComboBox<String> loaivemaybayBOX;
    private javax.swing.JTextField mamuaveTXT;
    private javax.swing.JTextField maveTXT;
    private javax.swing.JTable nguoimuaveTABLE;
    private javax.swing.JButton suaveBTN;
    private javax.swing.JButton themmuaveBTN;
    private javax.swing.JButton themveBTN;
    private javax.swing.JTable vemaybayTABLE;
    private javax.swing.JButton xoamuaveBTN;
    // End of variables declaration//GEN-END:variables
}
